### ISSUE TITLE
Project Poster 1st Draft

### ISSUE THREAD

**Issue by TaylorCWR** [Sheffield-iGEM/rEvolver#126]

**Comment by TheLostLambda** [comment]
@izzybel11 Do you know if you'll be around to keep working on this, or should we shuffle this to someone with a bit more time this week?

**Comment by TheLostLambda** [comment]
Done! https://drive.google.com/file/d/1USyaD3-hTYgB3gOfENX-u1pJK9zTWHoq/view?usp=sharing
