### ISSUE TITLE
Start documenting our iGEM story

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGEM/rEvolver#40]
This sort of information will come in handy when we are filling out our judging forms and Wiki!

We should document how our project changes over time in response to the feedback that we get from others we talk to! The meeting with Tuck was a good first step here and helped to narrow the focus down to a couple of systems, in a couple or organisms, to evolve a particular enzyme.

Very cool stuff, but should be in a Google Doc that links to other documents with meeting notes and more detail.

**Comment by pchalisa** [comment]
Already up-to-date but needs updating by people when a significant decision has been made about the project
